apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-image-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: flask-image-app
  template:
    metadata:
      labels:
        app: flask-image-app
    spec:
      containers:
      - name: flask-image-app-container
        image: rakeshbasnet/flask-s3file-upload:latest
        ports:
        - containerPort: 80
      imagePullSecrets:
      - name: dockerhub-secret
