apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-image-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-image-app
  template:
    metadata:
      labels:
        app: flask-image-app
    spec:
      containers:
      - name: flask-image-app-container
        image: rakeshbasnet/flask-s3file-upload:23
        env:
        - name: S3_BUCKET
          valueFrom:
            secretKeyRef:
              name: s3-credentials
              key: S3_BUCKET

        - name: S3_REGION
          valueFrom:
            secretKeyRef:
              name: s3-credentials
              key: S3_REGION
        - name: AWS_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: s3-credentials
              key: AWS_ACCESS_KEY
        - name: AWS_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: s3-credentials
              key: AWS_SECRET_KEY
        ports:
        - containerPort: 80
      imagePullSecrets:
      - name: dockerhub-secret
