apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-image-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: flask-image-app
  template:
    metadata:
      labels:
        app: flask-image-app
    spec:
      containers:
      - name: flask-image-app-container
        image: gcr.io/white-proxy-434723-d6/flask-image-app:latest
        ports:
        - containerPort: 80
      imagePullSecrets:
      - name: gcr-json-key
